version: '3.8'

services:
  website:
    image: patricklehmann/website:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: pause
        monitor: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - website-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.docker.stack.description=Patrick Lehmann's Personal Website"
      - "com.docker.stack.namespace=website"
      - "com.docker.stack.maintainer=Patrick Lehmann"
      - "com.docker.stack.version=1.0.0"

networks:
  website-network:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"
    labels:
      - "com.docker.stack.description=Website Network"
      - "com.docker.stack.namespace=website" 